// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:CosmosSim.DataGen.CosmosRepository.#ctor(Microsoft.Extensions.Configuration.IConfiguration,Microsoft.Extensions.Logging.ILogger)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:CosmosSim.DataGen.CosmosRepository.DeleteRecords(System.Collections.Generic.List{CosmosSim.DataGen.DailyDeviceReading})")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:CosmosSim.DataGen.CosmosRepository.CreateRecords(System.Collections.Generic.List{CosmosSim.DataGen.DailyDeviceReading})")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:CosmosSim.DataGen.CosmosRepository.ReadRecords(System.Collections.Generic.List{CosmosSim.DataGen.DailyDeviceReading})~System.Collections.Generic.List{CosmosSim.DataGen.DailyDeviceReading}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:CosmosSim.DataGen.CosmosRepository.UpdateRecords(System.Collections.Generic.List{CosmosSim.DataGen.DailyDeviceReading})")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:CosmosSim.DataGen.CosmosRepository.MergeRecordsStoredProc(System.Collections.Generic.List{CosmosSim.DataGen.DailyDeviceReading})")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:CosmosSim.DataGen.RecordsGenerator.Merge(CosmosSim.DataGen.DailyDeviceReading,CosmosSim.DataGen.DailyDeviceReading)~CosmosSim.DataGen.DailyDeviceReading")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:CosmosSim.DataGen.Program.Main()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:CosmosSim.DataGen.RecordsGenerator.Generate(System.Int32,System.Double)~System.Collections.Generic.List{CosmosSim.DataGen.DailyDeviceReading}")]
