// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:CosmosSim.Changefeed.Program.Main~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:CosmosSim.Changefeed.CosmosChangefeedRepository.#ctor(Microsoft.Extensions.Configuration.IConfiguration,Microsoft.Extensions.Logging.ILogger,CosmosSim.Changefeed.IStorage)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:CosmosSim.Changefeed.CosmosChangefeedRepository.HandleChangesAsync(System.Collections.Generic.IReadOnlyCollection{CosmosSim.DataGen.DailyDeviceReading},System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:CosmosSim.Changefeed.ADLSGen2Storage.SaveOverwriteIfExistsAsync(CosmosSim.DataGen.DailyDeviceReading)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:CosmosSim.Changefeed.ADLSGen2Storage.#ctor(Microsoft.Extensions.Configuration.IConfiguration,Microsoft.Extensions.Logging.ILogger)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:CosmosSim.Changefeed.ADLSGen2Storage.GetPathForRecord(CosmosSim.DataGen.DailyDeviceReading)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:CosmosSim.Changefeed.ADLSGen2Storage.GetPathForRecord(CosmosSim.DataGen.DailyDeviceReading)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:CosmosSim.Changefeed.CosmosChangefeedRepository.StartProcessorAsync~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:CosmosSim.Changefeed.CosmosChangefeedRepository.StopProcessorAsync~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:CosmosSim.Changefeed.CosmosChangefeedRepository.HandleChangesAsync(System.Collections.Generic.IReadOnlyCollection{CosmosSim.DataGen.DailyDeviceReading},System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:CosmosSim.Changefeed.Program.Main~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:CosmosSim.Changefeed.ADLSGen2Storage.SaveOverwriteIfExistsAsync(CosmosSim.DataGen.DailyDeviceReading)~System.Threading.Tasks.Task")]