name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build datagen
      working-directory: ./datagen
      run: dotnet build --configuration Release
    - name: Test datagen
      working-directory: ./datagen.Tests
      run: dotnet test
    - name: Build changefeed
      working-directory: ./changefeed
      run: dotnet build --configuration Release
    - name: Test changefeed
      working-directory: ./changefeed.Tests
      run: dotnet test
