name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: build datagen
      run: cd datagen
      shell: bash
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0
    - name: Build with dotnet
      run: dotnet build --configuration Release
